# Generated by Django 2.2.4 on 2019-09-01 03:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'voz_forum',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 9, 1, 3, 43, 20, 519522, tzinfo=utc))),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2019, 9, 1, 3, 43, 20, 519557, tzinfo=utc))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 9, 1, 3, 43, 20, 519522, tzinfo=utc))),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2019, 9, 1, 3, 43, 20, 519557, tzinfo=utc))),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('raw', models.TextField()),
                ('content_format', models.PositiveSmallIntegerField(choices=[(1, 'bbcode'), (2, 'markdown')])),
                ('order_number', models.PositiveIntegerField()),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=True)),
                ('delete_reason', models.CharField(max_length=128)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='api.User')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='api.Post')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='api.Thread')),
            ],
            options={
                'db_table': 'voz_post',
                'unique_together': {('thread', 'order_number')},
            },
        ),
    ]
