# Generated by Django 2.2.4 on 2019-09-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190905_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
