# Generated by Django 2.2.4 on 2019-09-05 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190905_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
