# Generated by Django 2.2.4 on 2019-09-05 16:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190905_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='last_post_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
